# Using container-based infrastructure
# sudo: false
# enable trusty beta
sudo: required
dist: trusty

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src
        - $HOME/x-tools
        - $HOME/zlib-install
        - $HOME/openssl-install

# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - gperf
            - libncurses5-dev
            - texinfo
            - help2man
            # - openssl
            # - zlib
            
# Handle git submodules yourself
git:
    submodules: false
    
# Use sed to replace the SSH URL with the public URL, then initialize submodules
# before_install:
#     - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#     - git submodule update --init --recursive
    
# Building crosstool-NG core
# install:
#     - cd crosstool-ng
#     - git checkout tags/crosstool-ng-1.21.0
#     - cp $TRAVIS_BUILD_DIR/ctng.config ./.config -f
#     - ./bootstrap
#     - ./configure --enable-local
#     - make
#     - make install

# Here is the list of all the standard samples tracked
# by the continuous integration system
env:
    # - CT_SAMPLE=mipsel-unknown-linux-gnu
    matrix:
        - SS_VER=v2.4.5
        - SS_VER=v2.4.1
        - SS_VER=v2.3.1
    global:
        - secure: Jb6Zg7zwuMwDquCiGLHf3Y5lbK20aD+Bxc0AqIfTM+Affjy2KmjnCdM2qtSt/WZOwxcaapYd+w+J1z3XvCMrIQql6EdtFNnvjQ7k6USeduvU/hdFaeiBMTHBayy2TSMo27afl6DfdJBfOP9f5NNLX0/FMXqtaM1OZ/GYVX2bge33o5BCz/325cfpShqoZYl9IGrHgzcA40dQxI04gQyCV6eXxb0K/B+wjTbsgDd3RPOPefw43nCAo5MzG1bN4T8Onn27eQfwvRLhXMpPQT4EnvpnO77Za6oPrIOq9rqePakWGt8zfUeTAuYfXMlBcZSQ0PLik7NamWkK8jj+Q4rATSQ94LgI8NRX2w2Opl4uIL/xvRFZslElIiqzyrEAYtXiJ36cVOpWaqKuU9nNw5N1nOB6EOu8irRVa1B5P4UoT0XRFzC5huKoQvxg21SKiMv/LGXUomYuGeu+NQi7uDGUH+1UVSZwOTuE3yVJXE8EYp9thwmCJrsfGIJBvqDzc2jRvslp+bpcjhVGJ7FCsuzcnRLpaKb2X2n+GSmVZCuMvWih66JB++1mVVjvkD2nqrg/9kOiPgEhYg3K2QWWNOs17mEzpZoGxGnZdWt5AoCxcgflqQ19cckiidJrxG/ZhgQEybwUgeaLp5am6kNjfoxY/zHcDDZl0eMHFVDzaNbFkMo=
# Building the standard samples
script:
    # - . ls -l $HOME
    - . $TRAVIS_BUILD_DIR/update-gh-pages.sh      # Load the travis environment
    # - ct-ng $CT_SAMPLE    # Configure the build
    # - ct-ng_travis_build  # Build the sample
    # - zlib_build
    # - openssl_build
    # - ss_build
    # - test

# On failure displaying the last lines of the log file
# after_failure:
#     - tail -n 1000 $TRAVIS_BUILD_DIR/config/build.log

# after_success: . $TRAVIS_BUILD_DIR/update-gh-pages.sh
